### ISSUE TITLE
编译报错了,好像是签名配置有问题

### ISSUE THREAD

**Issue by Zhaocyang** [youlookwhat/CloudReader#102]
ERROR: Could not get unknown property 'pStoreFile' for SigningConfig_Decorated{name=debug, storeFile=C:\Users\Zcyang\.android\debug.keystore, storePassword=android, keyAlias=AndroidDebugKey, keyPassword=android, storeType=jks, v1SigningEnabled=true, v2SigningEnabled=true} of type com.android.build.gradle.internal.dsl.SigningConfig.

**Comment by youlookwhat** [comment]
注释签名部分 https://github.com/youlookwhat/CloudReader/issues/82
