### ISSUE TITLE
玩Android链接打不开

### ISSUE THREAD

**Issue by longshanw** [youlookwhat/CloudReader#104]
net:ERR_CLEARTEXT_NOT_PERMITTED
网上找了解决方式：
从Android 9.0（API级别28）开始，默认情况下禁用明文支持。因此http的url均无法在webview中加载
<manifest ...>
    <uses-permission android:name="android.permission.INTERNET" />
    <application
        ...
        android:usesCleartextTraffic="true"
        ...>
        ...
    </application>
</manifest>

**Comment by youlookwhat** [comment]
好的，我完善一下 ，感谢😁

**Comment by youlookwhat** [comment]
已改 https://github.com/youlookwhat/CloudReader/commit/8cad5515045533c6dadf247489ddc071c9aa9f84 ，可以下载最新的包查看
