### ISSUE TITLE
列表卡顿问题还没有解决

### ISSUE THREAD

**Issue by chenxiaofei910714** [youlookwhat/CloudReader#107]
我下在最新版本看了下，在知识体系和导航数据这两页列表滑动加载时候比较卡，是因为列表用了分组流式布局这种样式的原因吗？我看你其他列表滑动很顺畅啊，就只有这两个

**Comment by youlookwhat** [comment]
是的，用了分组流式布局，导致部分item所占的高度过高，达不到复用，用了很多方式都解决不了。
那我下一版本把整体ui给换掉，来解决这个问题。

**Comment by chenxiaofei910714** [comment]
你用的是自己自定viewGourp还是三方开源的流式布局，用过官方谷歌开源的流式布局吗？


------------------ 原始邮件 ------------------
发件人: "Jinbeen"<notifications@github.com>;
发送时间: 2019年7月1日(星期一) 晚上8:58
收件人: "youlookwhat/CloudReader"<CloudReader@noreply.github.com>;
抄送: "陈晓飞"<chenxiao03@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [youlookwhat/CloudReader] 列表卡顿问题还没有解决 (#107)




是的，用了分组流式布局，导致部分item所占的高度过高，达不到复用，用了很多方式都解决不了。
 那我下一版本把整体ui给换掉，来解决这个问题。

**Comment by youlookwhat** [comment]
用的 官方谷歌开源的流式布局 ，起初用的三方开源的流式布局，但是都有这个问题。

**Comment by youlookwhat** [comment]
卡顿问题已解决，下载最新的包就好啦 https://fir.im/cloudreader
