### ISSUE TITLE
列表数据为空怎么显示占位符

### ISSUE THREAD

**Issue by zhengyi0049** [youlookwhat/CloudReader#108]
rercycleView数据源为空的时候要显示占位图，如何实现呢

**Comment by youlookwhat** [comment]
是的，有这个问题，我改一下

**Comment by youlookwhat** [comment]
@zhengyi0049 https://github.com/youlookwhat/CloudReader/commit/9814e5fd35955e9c6600062608a32f6347ded953 已处理返回数据未空，但没有显示占位图或显示的是网络错误的情况，拉最新的代码可以查看

**Comment by youlookwhat** [comment]
有什么问题再反馈吧~
