### ISSUE TITLE
RxBus在哪注册的

### ISSUE THREAD

**Issue by fishsoft** [youlookwhat/CloudReader#11]
看了半天也没找到RxBus是在哪里注册的，在哪里发送的

**Comment by youlookwhat** [comment]
你可以检索对应的code就出来了~

**Comment by fishsoft** [comment]
没找到

**Comment by youlookwhat** [comment]
RxBus.getDefault().toObservable(RxCodeConstants.JUMP_TYPE_TO_ONE, RxBusBaseMessage.class)
                .subscribe(new Action1<RxBusBaseMessage>() {
                    @Override
                    public void call(RxBusBaseMessage integer) {
                        mBinding.include.vpContent.setCurrentItem(1);
                    }
                });

建议网上查一下Rxbus相关用法，如还有问题请联系我
