### ISSUE TITLE
attempt to re-open an already-closed object: SQLiteDatabase:

### ISSUE THREAD

**Issue by threedeer** [youlookwhat/CloudReader#110]
你好，我用您这边的数据库模型有些时候会报这个错误
请问是什么原因导致的？

**Comment by youlookwhat** [comment]
是在使用这个应用时报的这个错吗，还是你把代码移植到你的项目时报的错呢？
我还没有遇到这样的情况，不过我查资料发现[有人遇到过](https://github.com/android/architecture-components-samples/issues/453)，我猜测可能的原因是版本号那里出现的问题。如果你是移植过去的，那么属于第一个版本，就需要更改我那里的版本号。

**Comment by youlookwhat** [comment]
也可以看下这个的处理方式：https://www.jianshu.com/p/7eb8a2466da3

**Comment by threedeer** [comment]
你好，谢谢解答，问题解决了。因为后台跟我接口返回字段不一致，导致实体类内容修改，但是没有修改数据库导致的。
再次感谢
