### ISSUE TITLE
想请教一个问题

### ISSUE THREAD

**Issue by hurist** [youlookwhat/CloudReader#111]
作者大大你好，我最近在参考你的这个项目写东西，看到OneRepository这里有点疑惑，就是如果按照这种方式写，rxjava会不会有内存泄露的问题呢？我看到其他的请求在viewmodel里都用CompositeDisposable做了处理，而OneRepository里就没有这一步了

**Comment by youlookwhat** [comment]
是的，OneRepository是有点多余，可以直接把请求数据viewmodel里，然后再使用addDisposable做处理。当初使用OneRepository是因为官方mvvm-databinding示例是这样的处理方式，现在看来没有这个必要。
