### ISSUE TITLE
关于ViewModel

### ISSUE THREAD

**Issue by yezihengok** [youlookwhat/CloudReader#113]
最近刚学习，不太明白 想问问作者ViewModel是怎么避免内存泄漏的呢

**Comment by youlookwhat** [comment]
不好意思 最近公司项目比较忙，回复的比较晚。
按我的理解，ViewModel并不是说使用了就避免内存泄漏了，而是要做一些操作。

1. ViewModel里面数据的变化通过观察者模式改变Activity中View的变化，而中间的媒介是`LiveData `。`LiveData`会和对应Activity的生命周期绑定`owner.getLifecycle().addObserver(wrapper)`；所以当Activity销毁的时候，如果数据返回了也是不会渲染数据的，而且对应的`LiveData`也会被移除`removeObservers`。

2. ViewModel里自带一个`onCleared()`方法，此方法会在Activity销毁时调用，使用者可以在这里做一些释放资源的操作。

**Comment by youlookwhat** [comment]
@yezihengok

**Comment by yezihengok** [comment]
thanks~~
