### ISSUE TITLE
为什么导入项目会报错ERROR: Unable to resolve dependency for ':app@debug/compileClasspath': Failed to transform artifact 'bottomsheet.aar

### ISSUE THREAD

**Issue by MirZou** [youlookwhat/CloudReader#114]
ERROR: Unable to resolve dependency for ':app@debug/compileClasspath': Failed to transform artifact 'bottomsheet.aar (com.cocosw:bottomsheet:1.3.1)' to match attributes {artifactType=jar}
Show Details
Affected Modules: app

ERROR: Unable to resolve dependency for ':app@debugAndroidTest/compileClasspath': Failed to transform artifact 'bottomsheet.aar (com.cocosw:bottomsheet:1.3.1)' to match attributes {artifactType=jar}
Show Details
Affected Modules: app

ERROR: Unable to resolve dependency for ':app@debugUnitTest/compileClasspath': Failed to transform artifact 'bottomsheet.aar (com.cocosw:bottomsheet:1.3.1)' to match attributes {artifactType=jar}
Show Details
Affected Modules: app

**Comment by youlookwhat** [comment]
再clone一下试试，我将`com.cocosw:bottomsheet`升级了

**Comment by MirZou** [comment]
@youlookwhat 可以运行了，谢谢

**Comment by youlookwhat** [comment]
@MirZou 有问题再提issue哈
