### ISSUE TITLE
Activity跳转动画在主题中style中 ->设置 windowAnimationStyle（华为 mate 8 设置不生效）

### ISSUE THREAD

**Issue by zhangi789** [youlookwhat/CloudReader#115]
Activity跳转动画在主题中style中 ->设置 windowAnimationStyle（华为 mate 8 设置不生效）

**Comment by youlookwhat** [comment]
是的，我也发现了，有些系统root那这个给剃掉了，用了他们自己的跳转动画

**Comment by zhangi789** [comment]
那你目前是怎么解决的,呢？
1:使用overridePendingTransition(.., ..)  只能看到进入动画，退出没有动画 。
2:Transition(转场动画)   getWindow().setEnterTransition(new Explode().setDuration(500));  像做Activity 跳转很不友好。（这种动画适合部分场景）

**Comment by youlookwhat** [comment]
是的。2只适合部分场景。
我是使用的是1，你要进入页面的时候使用`overridePendingTransition`，退出页面的时候也使用`overridePendingTransition`才行。

**Comment by youlookwhat** [comment]
```java
    @Override
    public void finish() {
        super.finish();
        // 第一个是进入的，第二个是退出的
        overridePendingTransition(R.anim.activity_down_in, R.anim.activity_down_out);
    }
```

**Comment by zhangi789** [comment]
你说的是对的，我测试一下可以，非常感谢！

**Comment by youlookwhat** [comment]
解决了就好，方便的话给个Star😁~

**Comment by zhangi789** [comment]
ok  必须的
