### ISSUE TITLE
setEmptyViewEnabled

### ISSUE THREAD

**Issue by zhangyuanzhao** [youlookwhat/CloudReader#117]
setEmptyViewEnabled 数据满10条的时候  好像没起作用

**Comment by youlookwhat** [comment]
设置了之后需要使用notifyDataSetChanged，照理说，显示的list数据和空布局是可以同时存在的。能不能看下你具体设置的代码

**Comment by zhangyuanzhao** [comment]
已经解决了，谢谢

**Comment by youlookwhat** [comment]
好的，有问题再提~
