### ISSUE TITLE
gank.io接口更新了

### ISSUE THREAD

**Issue by Imfondof** [youlookwhat/CloudReader#118]
当前项目使用的是旧版本的接口，gank提示使用新版本接口哦
作者打算什么时候更新，期待...

**Comment by youlookwhat** [comment]
恩恩，最近会更新为最新的，https://gank.io/api
欢迎关注哦~

**Comment by youlookwhat** [comment]
已更换，待发布最新版本
其中 
 - “干货|安卓”搜索api待作者修复
 - 每日干货无可替代api，页面待重写

**Comment by youlookwhat** [comment]
版本已更新~
https://www.coolapk.com/apk/127875
