### ISSUE TITLE
图片保存失败

### ISSUE THREAD

**Issue by ylmyg** [youlookwhat/CloudReader#129]
webview中保存图片，提示保存成功进云阅相册，查看相册并没有图片，手机是android11。

**Comment by ylmyg** [comment]
java.io.FileNotFoundException: /storage/emulated/0/云阅相册/https:--p9-juejin.byteimg.com-tos-cn-i-k3u1fbpfcp-eb5a9f0650904929ac86d5ff9b5b89d9~tplv-k3u1fbpfcp-zoom-in-crop-mark:1793:0:0:0.awebp?.jpg: open failed: EPERM (Operation not permitted) 
android11 没有权限了

**Comment by youlookwhat** [comment]
应该是没有适配，我最近更新一下发个新版本。还有之前很早就做了没有发布的功能(长按图标显示菜单)，也会一起带上。

到时候发布了再艾特你哈

**Comment by ylmyg** [comment]
目前在学习你的mvvm，databinding，写得很好，希望能尽早出新版本学习。

**Comment by youlookwhat** [comment]
前几天已适配了，可以拉最新的代码看哈 @ylmyg

**Comment by ylmyg** [comment]
收到

**Comment by ylmyg** [comment]
请问为什么我编译器总是提示
Cannot access 'androidx.databinding.Observable' which is a supertype of 'com.example.jingbin.cloudreader.databinding.FragmentContentBinding'. Check your module classpath for missing or conflicting dependencies
导致binding.ivSplash 像这样获取控制总是报错，但是又可以编译通过，github不清楚怎么发送图片 @youlookwhat
