### ISSUE TITLE
loadHotMovie Failure

### ISSUE THREAD

**Issue by idic779** [youlookwhat/CloudReader#13]
HTTP GET https://api.douban.com/v2/movie/in_theaters
 END HTTP (no body) END HTTP (no body)
D/Retrofit: javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
在浏览器输入API是有数据返回的，不过客户端解析出现问题

**Comment by youlookwhat** [comment]
豆瓣api请求是有限制的，每分钟超过一定次数就会请求失败，你可以过一会再请求或者更换ip再试试，如果请求有数据显示，之后又没了数据这就是api的问题

**Comment by youlookwhat** [comment]
@idic779 如果还有问题，请联系我 qq:770413277
