### ISSUE TITLE
请问源代码要在什么编辑器里打开呢

### ISSUE THREAD

**Issue by AJQBSC** [youlookwhat/CloudReader#131]
我放到AS里面运行不起来，还有需要配置写什么环境呢，能说一下吗，谢谢作者大大

**Comment by youlookwhat** [comment]
是在AS里打开的，如果运行不起来试着升级一下AS版本或者kotlin插件版本了，AS编译是会一些问题~

**Comment by AJQBSC** [comment]
> 是在AS里打开的，如果运行不起来试着升级一下AS版本或者kotlin插件版本了，AS编译是会一些问题~

哦哦好的，谢谢作者大大

**Comment by youlookwhat** [comment]
有问题再提哈
