### ISSUE TITLE
深色模式的问题

### ISSUE THREAD

**Issue by lingjianglin** [youlookwhat/CloudReader#132]
我用你的app 在小米手机上 使用，小米系统设置深色，但是app 设置浅色模式也没用，app整体还是深色模式

在华为mate40  pro上，同一款手机，下载你这个项目的网上的apk(release) 包，可以随系统 改变，但是下载你的项目 运行的
debug包，深色 模式和 浅色 模式的设置 也没啥用

**Comment by youlookwhat** [comment]
你是开屏页显示时深色模式有问题，还是进到应用里的深色模式有问题？开屏页始终是随着手机来的

**Comment by lingjianglin** [comment]
> 你是开屏页显示时深色模式有问题，还是进到应用里的深色模式有问题？开屏页始终是随着手机来的

都有问题额。

**Comment by youlookwhat** [comment]
能不能录个屏啥的，我刚在我的OPPO手机上运行了一下，没有发现问题，录个屏我仔细看看

**Comment by lingjianglin** [comment]
> 能不能录个屏啥的，我刚在我的OPPO手机上运行了一下，没有发现问题，录个屏我仔细看看

https://user-images.githubusercontent.com/7439509/218354521-46cf1f0d-0fe7-49c8-a1f4-62c83845f4ff.mp4、
上面这个视频是我用你的master 代码自己加签名打的release包的时候，

https://user-images.githubusercontent.com/7439509/218354844-b1f0fc5f-557a-4632-971e-f55a4d9306ad.mp4
这个视频是。直接下载https://www.coolapk.com/apk/com.example.jingbin.cloudreader 这个链接里的apk录的视频

在我的另外一个redmi8 pro手机中，如第一个视频所示

**Comment by youlookwhat** [comment]
我复现了，我修复下哈

**Comment by youlookwhat** [comment]
好的，我看看

**Comment by youlookwhat** [comment]
你要不要再拉最新的master测一下，我用公司的华为 oppo vivo 都试了一下，都没什么问题。。

**Comment by lingjianglin** [comment]
> 你要不要再拉最新的master测一下，我用公司的华为 oppo vivo 都试了一下，都没什么问题。。

今天尝试重新拉了master的代码，好像我的两款测试机 都OK。但是 之前下载的代码为啥就不得而知了，后面对比代码看看。
 
还有一个问题咨询 一下，我们的app 没有进行深色模式适配，
<img width="337" alt="WechatIMG439" src="https://user-images.githubusercontent.com/7439509/218650440-fe5c7b3f-43bb-48a3-81dc-a0896b9377e9.png">
但是系统设置为 深色模式后，app 进入了这个列表中， 
我在application中设置 了 AppCompatDelegate.setDefaultNightMode(AppCompatDelegate.MODE_NIGHT_NO)

**Comment by youlookwhat** [comment]
我理解是你不加深色模式的文件夹就好了：
`values-night`和 `drawable-night-xxhdpi`，或者还有其他的，然后系统就不会处理

**Comment by lingjianglin** [comment]
> 我理解是你不加深色模式的文件夹就好了： `values-night`和 `drawable-night-xxhdpi`，或者还有其他的，然后系统就不会处理

谢谢，我再看看吧，我们app里面没有这个文件夹， 但是还是被强制深色模式。不知道啥原因额，你的demo 有这两个文件夹，也没有进入上面图片的 那个自定义开启深色模式的 设置里，不知道为啥。不知道是否是厂商白名单 还是什么，因为微信好像也不再设置里面，可以自主设置深色还是浅色

**Comment by lingjianglin** [comment]
> 应该还和 `application` 里的 `theme` 有关系

application里面的theme是 “<style name="AppNormalTheme" parent="Theme.AppCompat.Light.NoActionBar">”

**Comment by youlookwhat** [comment]
也没问题呀

**Comment by lingjianglin** [comment]
> 也没问题呀

现象就是 mate 40pro 打开设置的深色模式，我们的app 强制 深色模式了，但是在 nova系列手机上 设置打开深色模式，app还是正常的 浅色模式，都是鸿蒙系统，这些厂商真坑爹

**Comment by youlookwhat** [comment]
我先关了，有问题再提了哈
