### ISSUE TITLE
全屏按钮跳转错误

### ISSUE THREAD

**Issue by 1018598742** [youlookwhat/CloudReader#14]
看视频那点击全屏按钮就跳回了之前页面并且横屏了

**Comment by youlookwhat** [comment]
你试试其他的播放视频地方，如果是好的就是自身的三方链接的问题，我这边不好处理，如果你在其他的App里打开这个视频没问题请告诉我，我会修正。谢谢~

**Comment by youlookwhat** [comment]
如还有问题请联系我~
