### ISSUE TITLE
【已更新至v1.5 】

### ISSUE THREAD

**Issue by youlookwhat** [youlookwhat/CloudReader#15]
1、App体积大小从16M降到5.8M！
2、将App里固定的图片以移动到七牛。
3、更改项目主页透明状态栏显示方式。
4、更改每日推荐图片显示规则，使其不重复显示。
5、更换过渡图图片。
6、代码优化；删除多余资源。

**Comment by xjf1128** [comment]
什么时候把retrofit 1.9升级为2.x呢，我网上找的retrofit版本基本都是2的，1.9的学习起来资料有点少哦

**Comment by youlookwhat** [comment]
恩   我正在更新，下一版本就是2.x的哦

**Comment by youlookwhat** [comment]
@xjf1128 已更新
