### ISSUE TITLE
 DataBindingHelper all library  后无变化?

### ISSUE THREAD

**Issue by a327037419** [youlookwhat/CloudReader#16]
generate 后 没有多选项

**Comment by youlookwhat** [comment]
去常见问题归纳里看详细用法:作为插件导入后，和GsonFormat的使用类似。在对应的Bean里，可自动生成@Bindable和notifyPropertyChanged(BR.title);。

**Comment by a327037419** [comment]
那个需要plugins里下载东西吗, 你那个jar包怎么用啊? GsonFormat 是需要下载插件的,然后
generate 复制文本进去!!

**Comment by youlookwhat** [comment]
导入插件有几种方式，jingbin.me  你看那篇常见问题归纳 ，第一个有说怎么导入和使用的~

**Comment by youlookwhat** [comment]
和生成 Get Set方法一个用法~可能有点混淆，我明天再纠正下

**Comment by youlookwhat** [comment]
@a327037419 http://jingbin.me/2017/11/23/%E5%BC%80%E5%8F%91%E4%B8%AD%E6%89%80%E9%81%87%E9%97%AE%E9%A2%98%E5%BD%92%E7%BA%B3/  看这里

**Comment by youlookwhat** [comment]
@a327037419 如还有问题请联系我qq:770413277
