### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by JairDavis** [youlookwhat/CloudReader#19]
很高兴能阅读到这么优秀的代码，其中有一部分不是很理解，希望作者能提供帮助。
```
    @ParamNames("count")
    private int count;
    @ParamNames("start")
```
```
@Documented
@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.FIELD)
public @interface ParamNames {
    String value();
}
```
这个注解的使用有什么样的作用，应用场景是怎么样的。
希望能提供一些资料供阅读参考。
谢谢。

**Comment by youlookwhat** [comment]
你好，最近准备换城市，有点忙，回复晚了请见谅。这关乎Retrofit的一些用法，可以参考这里http://www.jianshu.com/p/b64a2de066c3，之后我会更新到2.0，到时候再给你详细参考。
