### ISSUE TITLE
运行不了是怎么回事Error:(8, 51) 错误: 程序包com.example.jingbin.cloudreader.databinding不存在

### ISSUE THREAD

**Issue by 1040087877** [youlookwhat/CloudReader#2]
Error:(8, 51) 错误: 程序包com.example.jingbin.cloudreader.databinding不存在

Error:(20, 61) 错误: 找不到符号
符号:   类 ItemListBinding
位置: 类 Adapter

Error:(33, 88) 错误: 找不到符号
符号:   类 ItemAndroidBinding
位置: 类 AndroidAdapter

**Comment by youlookwhat** [comment]
我这边试了很多次没发现这个问题，我现在再重新试试~

**Comment by 1040087877** [comment]
显示找不到 com.example.jingbin.cloudreader.databinding包名，找不到databinding这个文件目录，麻烦您了

**Comment by youlookwhat** [comment]
你是下载完解压包跑起来就不行吗，看看配置什么的又没有改动，我刚又下载解压包跑了一遍，没发现这个问题啊，要不你再下载试试看行不行

**Comment by autoctl51** [comment]
确实是少上传文件了，编译有八九十个错误。：《 ， 你少上传了databinding文件夹，在代码仓库中也没有。
你在核对一下呗。：》

**Comment by Samuel-Hsieh** [comment]
确实没有
![default](https://cloud.githubusercontent.com/assets/10726614/21629423/1b8899b8-d263-11e6-9aa9-e1442ec62b47.png)

**Comment by youlookwhat** [comment]
好的，抱歉m(._.)m，可能是引入那个databindhelper 的jar 包导致的，需要配置简单配置一下，我现在在去公司的路上，到了马上核查，稍等下哦

**Comment by IcexTX** [comment]
`确实是少上传了databinding这个文件目录，我这边运行也是提示这个错误

**Comment by LyonUp** [comment]
下的是解压包 跑起来没问题 
界面很棒 开始看代码

**Comment by IcexTX** [comment]
我下载的也是解压包啊，怎么还是提示少了databinding这个文件目录？你的是在clone  or download-->download zip这里下载的吗？ @LyonUp

**Comment by youlookwhat** [comment]
【已解决】下载最新的包即可。神坑，原因是windows下databinding引入文字会有问题，而mac上没有..

**Comment by youlookwhat** [comment]
@IcexTX @1040087877 @Samuel-Hsieh

**Comment by IcexTX** [comment]
恩，我试试最新包

**Comment by 1040087877** [comment]
O(∩_∩)O谢谢

**Comment by Samuel-Hsieh** [comment]
大大辛苦了!谢啦，来研究啰
