### ISSUE TITLE
请问Bean模型的BR类是怎么来的呢？

### ISSUE THREAD

**Issue by GitHubAFeng** [youlookwhat/CloudReader#20]
大兄弟，RT，在bean模型中多次使用的BR类是怎么来的？在项目中找不到此类。是 DataBindingHelper.jar 的作用吗？我该怎么在项目中使用 DataBindingHelper.jar 呢？
谢谢~

**Comment by youlookwhat** [comment]
这关乎于DataBinding的用法，需要继承BaseObservable，具体用法可以看这篇文章：https://segmentfault.com/a/1190000002876984#articleHeader21  ；DataBindingHelper.jar的使用看这里的文章，第一条就是：http://jingbin.me/2017/11/23/%E5%BC%80%E5%8F%91%E4%B8%AD%E6%89%80%E9%81%87%E9%97%AE%E9%A2%98%E5%BD%92%E7%BA%B3/

**Comment by GitHubAFeng** [comment]
@youlookwhat 
OK！我明白了。  期待下一个版本 。  
有时我都被DataBinding的封装都绕晕了。
