### ISSUE TITLE
App体积大小从16M降到5.8M

### ISSUE THREAD

**Issue by JantHsueh** [youlookwhat/CloudReader#23]
你好，我在介绍中看到App体积大小从16M降到5.8M，能讲一下，是使用了哪些方法吗？？谢谢

**Comment by youlookwhat** [comment]
其实就是删掉一些多余的关联包，主要的就是图片，把比较大的图片都放到七牛了，代码占用的内存不大的

**Comment by JantXue** [comment]
还有个问题想请教一个，项目是使用MVVM架构吧，但是我翻了一下代码，好像没有找到ViewModel相关的类

**Comment by youlookwhat** [comment]
嗯，我理解的是vm指的是含有能绑定更新的xml文件，另一m还是model ，v是Activity ，有很多对MVVM框架理解的不太一样，我这段时间再多查查资料

**Comment by JantXue** [comment]
我看了很多文章，分享一下我的看法，如有不对，欢迎指正。我觉得MVVM中，view是activity和xml，vm是viewModel，m是model。这样的话，一些业务逻辑处理和分发，就可以放在vm中。model就只是提供数据

**Comment by youlookwhat** [comment]
是的  我也了解过，之后会研究后调整 近段时间有点忙~

**Comment by rosaemperor** [comment]
其实我也是奔着MVVM来看的，，等我找到activity看过之后，我的眼泪掉下来

**Comment by youlookwhat** [comment]
抱歉，我之前看了几篇写mvvm的文章，按照那里面的说法来实现的，可能很多文章写的有些差别，我理解的有偏差，以后我会纠正过来，最近工作有点忙，我会尽快更新~
