### ISSUE TITLE
大神，可否完善下注释

### ISSUE THREAD

**Issue by LingChenJie** [youlookwhat/CloudReader#24]
希望大神多添加下注释，能够整理一份流程图。也希望大神能够对框架做一份完整的框架设计，这样更能方便理解。

**Comment by GitHubAFeng** [comment]
我倒是觉得注释可以了，比起其它人……
只是觉得databinding有点烦琐。

**Comment by youlookwhat** [comment]
恩  已记下  近期找工作比较忙  之后会完善。
