### ISSUE TITLE
可否说下app的缓存模块

### ISSUE THREAD

**Issue by KarlMarxs** [youlookwhat/CloudReader#28]
初步看了下，是用ACache类来实现的，么有应用LRU算法。没有使用数据库，这快可否解释下你是怎么设计的呢？

**Comment by youlookwhat** [comment]
对啊，只是使用了ACache类，并没有使用数据库缓存之类的，不知你有什么高见。

**Comment by KarlMarxs** [comment]
你好，这块没有看法。还有个问题你项目中讲用到了DataBinding 框架，但是我们看你的项目，你在BaseActivity以及其他类中只是简单的通过DataBinding 映射一个bing类，省去了findviewbyid的过程，而没有用到数据绑定这块，请问你是怎么设计的？

**Comment by youlookwhat** [comment]
数据绑定在各自继承的子类里实现

**Comment by KarlMarxs** [comment]
你好，我理解DataBinding 框架功能拆分为：1代替注入框架2数据绑定，如在layout中使用binding语法“@{user.name}”如此。
我看了你的代码，使用框架只涉及到第一种功能：
mHeaderBinding = DataBindingUtil.inflate(LayoutInflater.from(getContext()), R.layout.header_item_everyday, null, false);
..............

这面只是疑意，你写的代码复用性好高，我目前在做framwork工作已经有1年半没有涉及app开发了，看你的代码挺好，赞

**Comment by youlookwhat** [comment]
遇到做framwork的大神了，我们是应用层，到framwork还有一段距离啊
