### ISSUE TITLE
首页轮播图无法显示

### ISSUE THREAD

**Issue by NullAerber** [youlookwhat/CloudReader#29]
如题，不知道是什么问题，我换两台手机都不行。
complietoolversion是25.0.2

**Comment by youlookwhat** [comment]
是的，我的这边也是，轮播图链接失效了，正在找适合替换的，你有适合的图片链接可供作为轮播图吗？

**Comment by NullAerber** [comment]
我这好像没有链接，不过图片倒是可以放在我服务器上。
对了，请问这个几个轮播图的链接在哪个文件修改？因为我昨天才开始看这个项目，还没有理清楚整体，谢谢～～

**Comment by youlookwhat** [comment]
昨晚解决了，将链接更换成https就好了。你看关于网络请求的包“http”就知道了。
