### ISSUE TITLE
get...Server()方法，每个都是copy一遍然后修改，应该统一封装

### ISSUE THREAD

**Issue by linfeizheng** [youlookwhat/CloudReader#3]
如题

**Comment by youlookwhat** [comment]
@linfeizheng 恩  起初是考虑到可能每个接口会有不同的配置，后来发现并没有，后面会慢慢优化。不止这里还有比较多的地方可以优化，比如传参抽象封装出来等。作为学习用，你可以取长补短哦

**Comment by youlookwhat** [comment]
@marialuisa3411 Sorry, there is no English version yet.
