### ISSUE TITLE
希望能增加链接分享功能

### ISSUE THREAD

**Issue by andrepeng** [youlookwhat/CloudReader#31]
有时看到一篇不错的文章，想分享给其他人，但是没有分享链接的功能

**Comment by youlookwhat** [comment]
你说的是 干货集中营的详情页吗，是有的啊，点击页面右上角的那个图标，有一个“分享至”就是的了

**Comment by youlookwhat** [comment]
如果没有的话，看最新的版本，v1.8.0之后添加的这个功能，当时我也觉得应该加上一个分享的功能好一些。

**Comment by andrepeng** [comment]
我说的是"大安卓"那一栏里的文章

**Comment by youlookwhat** [comment]
每一个WebView里都可以进行分享，大安卓里的文章也是可以分享的，你用的是哪个版本呢，是最新的版本的话有没有发现右上角的三个点？

**Comment by andrepeng** [comment]
我用的1.5，刚下了1.8的，但是安装失败，提示“更新包不兼容，需要卸载后重装，你也可以在应用商店装此应用”。我卸载了，重新安装还是同样安装失败，同样的提示。我的手机其实魅蓝note，android5.1

**Comment by youlookwhat** [comment]
你是下载最新的1.8.2吗

**Comment by youlookwhat** [comment]
我这边下载最新的是可以的，6.0 小米3，你再试试？

**Comment by youlookwhat** [comment]
@andrepeng 你那边解决了没？

**Comment by andrepeng** [comment]
我刚同步了最新的代码，可以分享文章了，通过android sudio安装到我手机上是可以的
