### ISSUE TITLE
XRecyclerView报错了。

### ISSUE THREAD

**Issue by lizhongze123** [youlookwhat/CloudReader#32]
你好，我把项目里的com.example.xrecyclerview.XRecyclerView拿出来用时，当我设置了这句
setLayoutManager(new StaggeredGridLayoutManager(2, StaggeredGridLayoutManager.VERTICAL));
滑动时就报错了，报的是 java.lang.IllegalArgumentException: Pixel distance must be non-negative
如果改为 setLayoutManager(new LinearLayoutManager(getActivity())); 
这样又没问题。在网上找了一下，没找到解决方案，请问这个你是怎么解决的呢？

**Comment by youlookwhat** [comment]
我项目中有这样用过吗？不好意思最近找工作有点忙，我有时间查查

**Comment by lizhongze123** [comment]
感谢回复。就是这个XRecyclerView，在你的项目里面没有问题，我拿出来用的时候如果设置瀑布流就会报错，但是设置其他又不会，就是想问下你是不是做了什么处理的？你有空的时候再看吧，谢谢

**Comment by 66668** [comment]
@lizhongze123 ,大神， 看看我的问题，@bindingAdapter在源码的什么位置设置的，告诉我一下，我dataBinding不太会用

**Comment by youlookwhat** [comment]
我之后又做了一下瀑布流的这个，这样设置的没问题：
layoutManager = new StaggeredGridLayoutManager(2, StaggeredGridLayoutManager.VERTICAL);
layoutManager.setOrientation(LinearLayoutManager.VERTICAL);
setLayoutManager(layoutManager);
你再试试吧
