### ISSUE TITLE
isApp属性

### ISSUE THREAD

**Issue by Igotyouinmysight** [youlookwhat/CloudReader#33]
大神，我看ViewBigImageActivity的时候看到你设置了一个isApp属性，并且根据该属性的true和false进行了不同的操作，但是我全局搜索的了一下，感觉全部都是设置的为false。请问是我看漏了么，另外就是他为true 或false的执行的步骤区别有什么吗

**Comment by youlookwhat** [comment]
这应该就是一个设置问题，没有很大的含义，不用太纠结，true 或false的区别你可以看源码哦~

**Comment by youlookwhat** [comment]
isApp 是本地图片还是网络图片的意思，因为基本是网络图片，所以都是传的false
