### ISSUE TITLE
ACache疑似bug

### ISSUE THREAD

**Issue by KarlMarxs** [youlookwhat/CloudReader#37]
Dear，youlookwhat：
         最近看了你ACache模块的实现，非常不错。但是在看代码中发现一个问题
         1 ACache.remove();
         2 ACache.put(),此时恰好需要清楚最久使用的一个文件，调用removeNext；在1中与已经执行f.delete()；重复执行是否会报异常；

          这个概率低(我这面没有网络，不知道会否报异常，如没有请你忽视)

**Comment by youlookwhat** [comment]
ACache类不是我写的，
你可以请教一下原作者~
