### ISSUE TITLE
item_one.xml中的一处疑问？

### ISSUE THREAD

**Issue by 66668** [youlookwhat/CloudReader#38]
我自己练习了大神的代码,发现这行总是提示bug,删除这行就正常运行，
位置：app--res--item_one.xml--<ImageView>的：android:showMovieImg="@{subjectsBean.images.large}"
提示bug:
Error:Execution failed for task ':app:compileDebugJavaWithJavac'.
> java.lang.RuntimeException: Found data binding errors.
****/ data binding error ****msg:Cannot find the setter for attribute 'android:showMovieImg' with parameter type java.lang.String on android.widget.ImageView.
file:E:\as_workspace\ISS\app\src\main\res\layout\item_one.xml
loc:35:40 - 35:64
****\ data binding error ****
求解答！！！

还有一处疑惑：databindinghelper.jar包为啥子放在工程下，而不放在module的libs下，求解答！！

**Comment by youlookwhat** [comment]
你那个可能是showMovieImg里具体操作的问题，这里是展示图片的控件，你可以看一下我的源码，因为我的没有出现这样的情况，所以我也不能具体和你分析。
databindinghelper.jar 相当于一个插件，而不是一个三方lib

**Comment by 66668** [comment]
问题解决了，没有引用ImgLoadUtil.java这个工具类，导致找不到。
