### ISSUE TITLE
app下载到本地,安装不了

### ISSUE THREAD

**Issue by jacknonebug** [youlookwhat/CloudReader#4]
https://pro-app-qn.fir.im/8559d96e22022ec22aa88c6afa815a9e551f2bbe.apk?attname=app-release.apk_1.0.apk&e=1483698969&token=LOvmia8oXF4xnLh0IdH05XMYpH6ENHNpARlmPc-T:bnuk6j5nw8T9fF3C1tylXElFr08= 下载后,解析程序包出现问题

**Comment by youlookwhat** [comment]
我这边可以，你的android版本是多少呢，只支持4.4以上的手机

**Comment by youlookwhat** [comment]
@jacknonebug 好了没

**Comment by youlookwhat** [comment]
如还有问题请联系我qq770413277
