### ISSUE TITLE
BR类找不到

### ISSUE THREAD

**Issue by 66668** [youlookwhat/CloudReader#41]
大神，能给你说说bean中的BR类是怎么生成的么，
我的登录步骤是：
（1）先按照你的bean模板创建自己的Bean（get set）
(2)用retrofit异步调用接口：
 Subscription sp = HttpClient.Builder.loginService().login(user.userName, user.password)
                .subscribeOn(Schedulers.io())
                .observeOn(AndroidSchedulers.mainThread())
                .subscribe(new Observer<UserInfoBean>() {...}
可是rebuild/clean 都提示该bean的BR找不到。还缺什么？

看这里！看这里！！！！！

**Comment by youlookwhat** [comment]
具体请看databinding 使用文档，Readerme里有链接
