### ISSUE TITLE
怎么没有处理异常的代码！！

### ISSUE THREAD

**Issue by 66668** [youlookwhat/CloudReader#42]
Subscription get = HttpClient.Builder.getDouBanService().getBook(mType, mStart, mCount)
                .subscribeOn(Schedulers.io())
                .observeOn(AndroidSchedulers.mainThread())
                .subscribe(new Observer<BookBean>() {}
这段代码如何添加解析{"code":0,"message":"","result":""}的代码
我想在登录的时候根据code状态判断是否登录，大神，求带

**Comment by youlookwhat** [comment]
希望你自己处理
