### ISSUE TITLE
activity调用基类很乱，希望优化下

### ISSUE THREAD

**Issue by 66668** [youlookwhat/CloudReader#45]
看过别人的上线项目，他们的activity都会继承baseActivity，做统一处理，比如退出，多界面退出，简化操作方法等，希望楼主也统一下，看着舒服撒~~~

**Comment by youlookwhat** [comment]
恩，后期会慢慢优化~
还有很多地方需要优化的，轮播图，数据的显示样式等。
有些基类的功能我没实现，考虑到很多人自己应用的项目，你可以自己实现的。
