### ISSUE TITLE
databinding不存在

### ISSUE THREAD

**Issue by lizhenqiang** [youlookwhat/CloudReader#47]
Error:(23, 51) 错误: 程序包com.example.jingbin.cloudreader.databinding不存在
小白求解 这个包在哪里
![1496819698 1](https://user-images.githubusercontent.com/22462911/26866554-1ee550ce-4b94-11e7-8d9d-2f316e07e279.jpg)

**Comment by youlookwhat** [comment]
这是系统自动生成的，检查是否是xml文件的错误

**Comment by youlookwhat** [comment]
更改包名也会导致报这个错，无法定位错误位置在哪，这也是databinding的一个弊端
