### ISSUE TITLE
运行报错，我的jdk是1.8版本

### ISSUE THREAD

**Issue by 1040087877** [youlookwhat/CloudReader#5]
![image](https://cloud.githubusercontent.com/assets/16516389/21715147/d682f3ea-d43d-11e6-84f4-a840383e49f5.png)

要运行的时候一直报上面的错误，好像和DataBindingHelper.jar 包有关系

错误代码：
Error:PARSE ERROR:
Error:unsupported class file version 52.0 
Error:...while parsing DataAction.class

Error:Execution failed for task ':app:transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: java.lang.RuntimeException: java.lang.RuntimeException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: java.lang.UnsupportedOperationException

**Comment by youlookwhat** [comment]
我的jdk也是1.8 DataBindingHelper.jar应该不会有问题  加我qq770413277  看具体什么情况

**Comment by 1040087877** [comment]
我重新clone下项目，运行看下会不会有问题，不行在看吧

**Comment by youlookwhat** [comment]
恩  有问题联系我

**Comment by 1040087877** [comment]
ok 重新clone 一份 成功运行了

**Comment by youlookwhat** [comment]
恩，可以follow我，有问题随时反馈哦。
