### ISSUE TITLE
关于内存泄漏

### ISSUE THREAD

**Issue by Gundam0079** [youlookwhat/CloudReader#50]
举一个例子
listener是匿名内部类会持有UI层比如fragment的引用 
如果网络比较慢listener异步请求 又销毁了fragment就会有泄露的风险
共同学习 现在已知的解决方法就是利用弱引用 加静态匿名内部类的方法避免
 public void showBanncerPage(final RequestImpl listener) {
        Subscription subscription = HttpUtils.getInstance().getDongTingServer().getFrontpage()
                .observeOn(AndroidSchedulers.mainThread()).subscribeOn(Schedulers.io())
                .subscribe(new Observer<FrontpageBean>() {
                    @Override
                    public void onCompleted() {
                    }

                    @Override
                    public void onError(Throwable e) {
                        listener.loadFailed();
                    }

                    @Override
                    public void onNext(FrontpageBean frontpageBean) {
                        listener.loadSuccess(frontpageBean);
                    }
                });
        listener.addSubscription(subscription);
    }

**Comment by youlookwhat** [comment]
嗯恩  没有很严谨，我再完善一下，那个页面在首页里，退出的话就退出App了，不过有其他子页面用到就内存泄漏了。非常感谢提出！
