### ISSUE TITLE
rxBux的bug

### ISSUE THREAD

**Issue by wyvector** [youlookwhat/CloudReader#52]
你好！我在运行代码的时候，针对
// 首页跳转到电影栏
    public static final int JUMP_TYPE_TO_ONE = 1;
的这个事件，做了测试，发现由于rxBus的bug，会导致进入多少次MainActivity，就会多出多少次该事件的响应：即，如果这个事件被post一次，而进入了MainActivity 3次，那么call事件变调起3次。
应该是由于在退出 MainActivity的时候，没有对其进行释放导致的。
但是我对rxBus理解还不够深入，请问如果释放掉呢

**Comment by youlookwhat** [comment]
.addSubscription(subscription); 加上这个就好了  这是释放的，你看看基类里面。因为首页一直存在所以没有加这个。
