### ISSUE TITLE
“项目主页”页面的两个布局问题

### ISSUE THREAD

**Issue by ics042** [youlookwhat/CloudReader#54]
**项目主页**页面发现如下两个问题， 具体见如下截图蓝框：
1. 当头部CollapsingToolbarLayout中的图片完全收缩后，标题`云阅`只显示了一半
2. 底部`用到的开源库`CardView被挤出屏幕外，无法显示不完全

第二个问题`用到的开源库`被挤出屏幕外，我尝试了很多办法，始终没有解决，感觉应该是`layout_scrollFlags`的bug，最后没办法通过改`layout_scrollFlags`为`enterAlways`来规避了。
```
app:layout_scrollFlags="scroll|enterAlways"
```
第一个问题在我这开发环境无法复现，也就无从定位了。

![cloudreader](https://user-images.githubusercontent.com/22568528/31313725-b8801796-ac47-11e7-95c3-e8fd081d3e69.PNG)

**Comment by youlookwhat** [comment]
还没考虑到这种机型的问题，我有机会测试测试~

**Comment by xjf1128** [comment]
第一个问题，模拟机与真机Android7.0，8.0会出现，但5.1都没这个bug。我把状态栏改为不透明就行了，但牺牲美观了

**Comment by youlookwhat** [comment]
@ics042 我把design升级了就变成这样了，初步断定是design升级导致的。现在在完善，谢谢

**Comment by ics042** [comment]
谢谢！
