### ISSUE TITLE
我想找一个标准的MVVM模式的例子学习

### ISSUE THREAD

**Issue by KaiXuan666** [youlookwhat/CloudReader#57]
但是你的这个项目貌似并不是MVVM架构？我找不到ViewModel类

**Comment by youlookwhat** [comment]
很抱歉 因为项目写的早，MVVM当时还存在些许争议，我按照我的想法来写的 现在知道不标准。我之后会改成标准的MVVM，因为近期公司项目比较忙，所以还要一段时间，但不会太长时间，到时候好了再@你。
另有个资料可以参考（https://github.com/youlookwhat/ProjectPatternStudy），希望对你能有帮助

**Comment by RMaple** [comment]
大佬做的很厉害，我本来也想仿写WANGYIYUN，朋友推荐了我这个项目，我要好好学习

**Comment by youlookwhat** [comment]
@KaiXuan666 已基本完善
