### ISSUE TITLE
你好，可以参考你的项目吗？

### ISSUE THREAD

**Issue by DreamerLeon** [youlookwhat/CloudReader#58]
想自己做一些架构测试，UI还有一些api可以直接用你的吗？会注明参考你的项目得

**Comment by youlookwhat** [comment]
大体样式可以引用，里面的部分页面最好不要完全使用，比如电影列表和电影详情页，看你是用到什么场合，如果自己玩玩就另当别论，发表出来的话就要修改一下。使用的话还请写上参考项目，谢谢

**Comment by DreamerLeon** [comment]
@youlookwhat 好的会注明参考项目的，Api部分自己做测试github上传应该没问题吧？

**Comment by youlookwhat** [comment]
@DreamerLeon api是干货集中营和豆瓣的，可以随便用~
