### ISSUE TITLE
哥哥,是否考虑加上缓存实现的idea

### ISSUE THREAD

**Issue by yungelee** [youlookwhat/CloudReader#59]
今天down下来玩了下, 缓存没做啊, 好费流量啊...

**Comment by youlookwhat** [comment]
里面有很多图片是很耗流量，后期考虑吧~

**Comment by yungelee** [comment]
再看代码，你的xrecyclerview中的onTouchEvent
`
  if (mRefreshHeader.getVisiableHeight() > 0 && mRefreshHeader.getState()
                            < YunRefreshHeader.STATE_REFRESHING) {
                        return false;
                    }

`
具体有什么用处？让下次事件不来吗，但是试着修改没发现有什么效果啊？烦请指教，thanks

**Comment by youlookwhat** [comment]
这个最新的改为处理MD滑动处理的事务的；
```if (isOnTop() && pullRefreshEnabled && appbarState == AppBarStateChangeListener.State.EXPANDED) {```
因为这里限制了，所以你没有使用到这个组件的话修改就没有效果。
你可以在GitHub查到这个库：[XRecyclerView](https://github.com/XRecyclerView/XRecyclerView)
里面时常有更新

**Comment by yungelee** [comment]
哦，我想先把你的代码读一遍再说，那个库的代码有点躲。and what’s the hell of "MD滑动处理的事务"?

**Comment by youlookwhat** [comment]
就是一个控件的使用可能对刷新有影响，原作者处理了一下
