### ISSUE TITLE
我觉得图片保存那里可以添加一个Toast提示

### ISSUE THREAD

**Issue by Changle8821** [youlookwhat/CloudReader#6]

**Comment by youlookwhat** [comment]
@Changle8821 你说的是哪种提示呢，那里是有提示的~

**Comment by Changle8821** [comment]
在福利那里，图片右下角的保存，个人觉得可以在点击保存后页面提示已经保存之类的消息。最近在学习安卓用过Toast提示就想到了可以加提示，个人觉得。

**Comment by youlookwhat** [comment]
噢噢  我也想到了，谢谢提醒，最近正准备解决，还有优化那个保存键的点击效果，像网易云音乐那样。可以follow我，有什么新的想法都可以说哈。

**Comment by Changle8821** [comment]
好的
