### ISSUE TITLE
请教下作者一个问题

### ISSUE THREAD

**Issue by qzqs** [youlookwhat/CloudReader#61]
我导入项目后出现
Error:(20, 0) Could not get unknown property 'pToken' for BuildType_Decorated{name=release, debuggable=false, testCoverageEnabled=false, jniDebuggable=false, pseudoLocalesEnabled=false, renderscriptDebuggable=false, renderscriptOptimLevel=3, minifyEnabled=false, zipAlignEnabled=true, signingConfig=null, embedMicroApp=true, mBuildConfigFields={}, mResValues={}, mProguardFiles=[], mConsumerProguardFiles=[], mManifestPlaceholders={}} of type com.android.build.gradle.internal.dsl.BuildType.
<a href="openFile:C:\Users\Administrator\Desktop\AllNetDemo\yueyun\CloudReader\CloudReader\app\build.gradle">Open File</a>
按照网上的方法做了修改还是不行，请问下我该怎么解决

**Comment by youlookwhat** [comment]
@qzqs 将pToken用 “” 代替，因为pToken是个人的我处理掉了。

**Comment by qzqs** [comment]
谢谢~
