### ISSUE TITLE
请叫一个问题？

### ISSUE THREAD

**Issue by qzqs** [youlookwhat/CloudReader#62]
作者你好，为什么我现在获取豆瓣V2数据都是返回400错误呢？我看了豆瓣的API获取最新电影资讯也是直接通过http://api.douban.com/v2/movie/in_theaters 来获取的，网页也是可以获取到的，为什么通过手机获取就不行了，难道是需要申请key么？

**Comment by qzqs** [comment]
02-26 14:54:26.487 29086-29763/yang.nesnd D/OkHttp: --> GET https://api.douban.com/v2/movie/in_theaters http/1.1
02-26 14:54:26.487 29086-29763/yang.nesnd D/OkHttp: User-Agent: Android, xxx
02-26 14:54:26.487 29086-29763/yang.nesnd D/OkHttp: Accept: application/json
02-26 14:54:26.487 29086-29763/yang.nesnd D/OkHttp: --> END GET
02-26 14:54:26.555 29086-29763/yang.nesnd I/System: core_booster, getBoosterConfig = false
02-26 14:54:26.607 29086-29763/yang.nesnd I/System: core_booster, getBoosterConfig = false
02-26 14:54:26.798 29086-29763/yang.nesnd D/OkHttp: <-- 400 Bad Request https://api.douban.com/v2/movie/in_theaters (311ms)

总是这个错误，作者指点一下么？

**Comment by qzqs** [comment]
02-26 15:02:22.233 31206-734/yang.nesnd D/OkHttp: --> GET https://api.douban.com/v2/movie/in_theaters http/1.1
02-26 15:02:22.233 31206-734/yang.nesnd D/OkHttp: User-Agent: Android, xxx
02-26 15:02:22.233 31206-734/yang.nesnd D/OkHttp: Accept: application/json
02-26 15:02:22.233 31206-734/yang.nesnd D/OkHttp: --> END GET
02-26 15:02:22.338 31206-734/yang.nesnd I/System: core_booster, getBoosterConfig = false
02-26 15:02:22.395 31206-734/yang.nesnd I/System: core_booster, getBoosterConfig = false
02-26 15:02:22.606 31206-734/yang.nesnd D/OkHttp: <-- 400 Bad Request https://api.douban.com/v2/movie/in_theaters (373ms)
02-26 15:02:22.607 31206-734/yang.nesnd D/OkHttp: Date: Mon, 26 Feb 2018 07:02:22 GMT
02-26 15:02:22.607 31206-734/yang.nesnd D/OkHttp: Content-Type: application/json; charset=utf-8
02-26 15:02:22.607 31206-734/yang.nesnd D/OkHttp: Content-Length: 70
02-26 15:02:22.607 31206-734/yang.nesnd D/OkHttp: Connection: keep-alive
02-26 15:02:22.607 31206-734/yang.nesnd D/OkHttp: Keep-Alive: timeout=30
02-26 15:02:22.607 31206-734/yang.nesnd D/OkHttp: Expires: -1
02-26 15:02:22.607 31206-734/yang.nesnd D/OkHttp: X-DAE-Node: sindar12c
02-26 15:02:22.607 31206-734/yang.nesnd D/OkHttp: X-DAE-App: movie
02-26 15:02:22.607 31206-734/yang.nesnd D/OkHttp: Server: dae
02-26 15:02:22.607 31206-734/yang.nesnd D/OkHttp: {"msg":"Invalid request","code":999,"request":"GET \/v2\/in_theaters"}
为什么总是发回未知错误，是不是现在豆瓣API已经不给获取数据了？

**Comment by youlookwhat** [comment]
网页可以直接获取的话app端基本是没什么问题的，你看我的那里面基本没什么多余的处理。值得注意的是，接口有请求限制，一个ip短时间内多次请求会产生错误

**Comment by qzqs** [comment]
难道是我在打开你的APP以后，同一个局域网下再测试我的APP获取数据以后造成了同一个ip的多次请求了，但是奇怪就是每次你的APP都是可以显示数据，而我的就是400...

**Comment by youlookwhat** [comment]
我的首页使用的是缓存，详情页才调用的接口。你使用4g再试试，如果可以的话就是被限制了

**Comment by qzqs** [comment]
还是不行哦，怎么都获取不到，已经不知道怎么去解决了~ 谢谢作者回答~
