### ISSUE TITLE
缺少gradle.properties文件

### ISSUE THREAD

**Issue by jakiejiang** [youlookwhat/CloudReader#64]
缺少gradle.properties文件,报错信息为
Error:java.util.concurrent.ExecutionException: com.android.tools.aapt2.Aapt2Exception: AAPT2 error: check logs for details
Error:Execution failed for task ':app:mergeDebugResources'.
> Error: java.util.concurrent.ExecutionException: com.android.tools.aapt2.Aapt2Exception: AAPT2 error: check logs for details
手动添加gradle.properties文件,并在文件中加入android.enableAapt2 = false后仍然报错,求解

**Comment by youlookwhat** [comment]
@jakiejiang 添加gradle.properties文件，我的gradle.properties文件：
```java
# 签名信息
pStoreFile = xxxxxxxxxxxxx
pStorePassword = xxxxxxxxxxxxx
pKeyAlias = xxxxxxxxxxxxx
pKeyPassword = xxxxxxxxxxxxx

# 更新提醒token
pToken = ""

```
删除签名信息的相关配置，pToken = ""即可

**Comment by jakiejiang** [comment]
字符串中包含百分号,位于strings.xml文件,编译时会报错

**Comment by youlookwhat** [comment]
@jakiejiang 第一个问题解决了吗？百分号的问题是你自己加的百分号吗，我这边编译是没有发现这么问题的。

**Comment by jakiejiang** [comment]
第一个问题解决了,百分号是url里的百分号,string_url_update_log和string_url_faq,加双百分号即可,现在已经可以成功编译了.

**Comment by 1-riverfish** [comment]
求助,编译的时候报错,错误提示为非法的表达式开始,文件定位在buildconfig.java,代码update_token未赋值
public static final String UPDATE_TOKEN =  ;

**Comment by youlookwhat** [comment]
在build.gradle下面找到pToken变量，替换为“”

**Comment by 1-riverfish** [comment]
已经替换了,仍然报错

**Comment by youlookwhat** [comment]
加我qq:770413277，我截图给你。后期我会放怎么解决这个问题的文档，其实就是gradle配置的问题

**Comment by youlookwhat** [comment]
@jakiejiang @1-riverfish  项目根目录新建 gradle.properties 文件，里面添加pToken = "xx"

**Comment by youlookwhat** [comment]
@jakiejiang @1-riverfish 已更正，下载最新的包即可!
