### ISSUE TITLE
安装apk

### ISSUE THREAD

**Issue by zhangjiameng** [youlookwhat/CloudReader#65]
Error:Execution failed for task ':app:transformNativeLibsWithStripDebugSymbolForDebug'.
> A problem occurred starting process 'command 'D:\Android_sdk\ndk-bundle\toolchains\aarch64-linux-android-4.9\prebuilt\windows-x86_64\bin\aarch64-linux-android-strip''

**Comment by zhangjiameng** [comment]
Error:Execution failed for task ':app:transformNativeLibsWithStripDebugSymbolForDebug'.
> A problem occurred starting process 'command 'D:\Android_sdk\ndk-bundle\toolchains\aarch64-linux-android-4.9\prebuilt\windows-x86_64\bin\aarch64-linux-android-strip''

**Comment by youlookwhat** [comment]
重新clone最新的包试试
