### ISSUE TITLE
导入项目build失败

### ISSUE THREAD

**Issue by five-lei** [youlookwhat/CloudReader#68]
Could not get unknown property 'pToken' for BuildType_Decorated{name=release, debuggable=false, testCoverageEnabled=false, jniDebuggable=false, pseudoLocalesEnabled=false, renderscriptDebuggable=false, renderscriptOptimLevel=3, minifyEnabled=false, zipAlignEnabled=true, signingConfig=null, embedMicroApp=true, mBuildConfigFields={}, mResValues={}, mProguardFiles=[], mConsumerProguardFiles=[], mManifestPlaceholders={}} of type com.android.build.gradle.internal.dsl.BuildType.

**Comment by youlookwhat** [comment]
我现在再测一下 ，之前是好的

**Comment by youlookwhat** [comment]
@five-lei 这个问题已经解决了。克隆最新的包再跑一下。或者你删除项目中有关“ pToken”属性的配置信息。

**Comment by five-lei** [comment]
@youlookwhat 可以了，，谢谢啦，，

![image](https://user-images.githubusercontent.com/28173605/38909656-22a8bd98-42f8-11e8-80b0-a433c886d144.png)
背景为白色时，透明状态栏的字体颜色没变，

**Comment by youlookwhat** [comment]
恩 这个统一设置的是白色。因为有时候需要是白色有时候需要是黑色，而且要根据图片的颜色来设置，得不偿失
