### ISSUE TITLE
内存泄漏

### ISSUE THREAD

**Issue by stevenwsg** [youlookwhat/CloudReader#70]
设计的很好，MD风格运用的恰当自如
但是内存泄漏比较严重啊~~~~~~~~~

**Comment by youlookwhat** [comment]
具体哪个地方呢，感觉还好啊，一个webview还有一个电影详情页有点，其他的也没有检测到。就是整体框架缓存的页面太多了，有八个fragment一直在内存，所以感觉内存一直没有降

**Comment by stevenwsg** [comment]
感谢回复~~~~~~~~~~~
我才刚开始读你的源码，感谢你的开源~~~
在运行的时候 ，看日志 ，内存频繁GC。

我还是个学生，有错误的地方还请谅解   呜呜呜~~~~~~

闪屏页 TransitionActivity  里面创建了两个匿名类（匿名Handler）
匿名内部类持有外部类的引用，会造成内存泄露

代码：

//        new Handler().postDelayed(new Runnable() {
//            @Override
//            public void run() {
//                mBinding.ivDefultPic.setVisibility(View.GONE);
//            }
//        }, 1500);


        //匿名内部类持有外部类的引用，造成内存泄露
//        new Handler().postDelayed(new Runnable() {
//            @Override
//            public void run() {
//                toMainActivity();
//            }
//        }, 3500);



我觉得应该在最前面 写个 Handler，并在onDestory()中移除 所有消息


public Handler handler=new Handler(){
    @Override
    public void handleMessage(Message msg) {
        super.handleMessage(msg);

        switch (msg.what){
            case 0:
                mBinding.ivDefultPic.setVisibility(View.GONE);
                break;
            case 1:
                toMainActivity();
                break;
        }

    }
};

发送消息：
handler.sendEmptyMessageDelayed(0,1500);
handler.sendEmptyMessageDelayed(1,3500);



@Override
protected void onDestroy() {
    super.onDestroy();
    //清除所有的消息
    handler.removeCallbacksAndMessages(true);
}

**Comment by youlookwhat** [comment]
感谢提醒，是有这个问题，之前写的匆忙没有考虑到，现在已经修复了，详见[TransitionActivity](https://github.com/youlookwhat/CloudReader/blob/develop_2.0/app/src/main/java/com/example/jingbin/cloudreader/ui/TransitionActivity.java)。有其他的地方希望继续提意见，谢谢~

```java
static class MyHandler extends Handler {
        private WeakReference<TransitionActivity> mOuter;

        MyHandler(TransitionActivity activity) {
            mOuter = new WeakReference<>(activity);
        }

        @Override
        public void handleMessage(Message msg) {
            super.handleMessage(msg);
            TransitionActivity outer = mOuter.get();
            if (outer != null) {
                something(outer, msg);
            }
        }

        private void something(TransitionActivity outer, Message msg) {
            switch (msg.what) {
                case 0:
                    outer.mBinding.ivDefultPic.setVisibility(View.GONE);
                    break;
                case 1:
                    outer.toMainActivity();
                    break;
                default:
                    break;
            }
        }
    }
```

**Comment by stevenwsg** [comment]
恩恩~~~~~~~~~~~
感谢你的开源~~~~~~~

**Comment by youlookwhat** [comment]
@linyingfa 只有当Activity的finish()方法被调用时，对象才会被销毁。好像没什么毛病。
