### ISSUE TITLE
总感觉MVVM-DataBinding相对来说没有更好用。。

### ISSUE THREAD

**Issue by MAYBreath** [youlookwhat/CloudReader#72]
之前最早5年前开发过android的大项目，那时候还是eclipse的时代，eclipse的开发体验跟翔一样的。做完项目后就不想再做android了。
目前借着这个项目打算重新开始看看as，看了下mvvm各种绑定啊 ，感觉好像更加繁琐了。。要建bean啊，viewmodel啊，Adapter啊，每多一个接口改动就要弄一大堆，而且出错又很难定位，感觉好有点本末倒置，不知道是不是我的错觉，我记得以前好像更简单一点。
可能是这么多年没做我又成新手了的感觉。。一切都好陌生，作者请不要介意。。

因为现在跟着这个项目试着加个接口，相比起来，感觉以前的代码会更清晰。
比如试着跟着建个Viewmodel，看了下项目ViewModel的movie里面OneViewModel，这个不是电影的model吗，怎么里面还有个OneRepository，这干货是。。。。？

作者的界面效果真的很棒，真的很想深入学习下，可是前前后后拖了一年多，始终无法下手，
可能做的东西比较多，老小白希望能拆分一点简单的出来。。比如就单个电影模块之类的最小单元。。

抱歉都是我在发牢骚，给作者添麻烦了。。。

**Comment by youlookwhat** [comment]
原来是前辈，失敬失敬。

是的，mvvm觉得现在还是先了解为好，我也没有在项目中应用，因为出错很难定位，其他的错误也可能导致databinding报错。我建议还是先以MVP为主，databinding还是辅助，现在我觉得项目还是不是非常纯粹的MVVM。相比之前的MVC，mvp和mvvm加的文件是比较多，但是结构比较清晰，处理ui的和处理数据的分离了，不会导致代码混乱。

OneRepository和OneViewModel是我这边没有规范化，可能导致了误解，抱歉。我是打算学Dagger2的，这可能不太规范，建议先看[福利页面](https://github.com/youlookwhat/CloudReader/blob/master/app/src/main/java/com/example/jingbin/cloudreader/ui/gank/child/WelfareFragment.java)，OneRepository会再完善一下，比如去掉什么的。

大家一起学习，有问题就说，客气了~

**Comment by MAYBreath** [comment]
非常感谢，逛了下之前的作者的项目，发现有独立拆出音乐详情页ScrollShape，这个就非常棒了，最小单元适合我重新上手，不知道这个DEMO近一年有没有更新，貌似有点bug。
不过一个小DEMO开始，会简单很多，有空的话希望能多拆分出来，对新手和老小白帮助非常大，这个项目好多东西都可以拆出来学习的，全部放一起有点可惜。
再次感谢。

**Comment by youlookwhat** [comment]
对了，之前你说的那个OneRepository我今天看了，是相对标准的mvvm,可能第一次看不太适应。那个单独做出来的demo我再看看，之前都是好好的。

**Comment by youlookwhat** [comment]
ScrollShape改好了，是因为页面内图片的url失效了，已经修正了~

**Comment by youlookwhat** [comment]
恩恩，帮忙到你我感到非常高兴~

**Comment by MichaelXcy** [comment]
@youlookwhat 大神你好，首先感谢你的开源项目，给予了我很大的帮助。正在学习安卓，以前都是用eclipse开发，现在从as入手，像学习下MVP以及MVVM模式的开发。

编译了这个项目的最新代码跑起来，内容是没问题的，真棒。
但是好像Leaks 这个模块里面会提示有内存泄漏，主要是ViewBigImageActivity 里面泄漏。这个问题有时间的话麻烦帮忙查一下是什么原因？多谢。

**Comment by zofnk** [comment]
@youlookwhat 并且在一些V层中..例如福利界面..都是直接new XXXViewModel();这种方式,我看了网上的一些分析, 不是说不要以new的方式(尽量以`ViewModelProviders.of(this).get(XXXViewModel.class);`)实例化的么...请问一下为啥这样写....

**Comment by youlookwhat** [comment]
@zofnk 你看的这个类不是很规范，相对规范的请看这个类，[OneFragment.java](https://github.com/youlookwhat/CloudReader/blob/master/app/src/main/java/com/example/jingbin/cloudreader/ui/movie/OneFragment.java)，不知道你说的是不是这样的形式。

**Comment by zofnk** [comment]
@youlookwhat  嗯 感谢你的这项目给我挺多启发 ,这个页面没有分页的 , 可否能有个规范的MVVM的带有分页的页面呢 , 我卡在ViewModel和请求的分页状态变化这里了...想要有个比较完善的封装 , 尝试了挺多但是都不是很好

**Comment by youlookwhat** [comment]
由于之前的架构不是很规范，现已全部整理了一遍
都是已``ViewModelProviders.of(this).get(XXXViewModel.class);)``形式实例化的。
有需要的可以查看最新代码~
