### ISSUE TITLE
发现了个bug

### ISSUE THREAD

**Issue by Henrylhd** [youlookwhat/CloudReader#73]
干货定制页面点击选择分类crash，我看报错是java.lang.AbstractMethodError: abstract method "android.view.MenuItem android.support.v4.internal.view.SupportMenuItem.setAlphabeticShortcut(char, int)"  定位在CustomFragment的initHeader（）方法，希望作者能抽空能完善下，谢谢！

**Comment by youlookwhat** [comment]
恩恩 感谢提醒，已经完善了，Android4.4 6.0 7.1的手机测试了没问题，你可以去[develop_2.0](https://github.com/youlookwhat/CloudReader/tree/develop_2.0)分支上下载最新的包，或者等我再更新应用
