### ISSUE TITLE
最新版本直接运行会报错

### ISSUE THREAD

**Issue by fengrenai** [youlookwhat/CloudReader#74]
Could not get unknown property 'pStoreFile' for SigningConfig_Decorated{name=debug, storeFile=/Users/***/.android/debug.keystore, storePassword=android, keyAlias=AndroidDebugKey, keyPassword=android, storeType=/Users/***/.android/debug.keystore, v1SigningEnabled=true, v2SigningEnabled=true} of type com.android.build.gradle.internal.dsl.SigningConfig.

**Comment by fengrenai** [comment]
注释掉signconfig就可以了

**Comment by youlookwhat** [comment]
配置的签名文件，这个很早就有了，基本都知道，下载我再写个注释
