### ISSUE TITLE
大神你好，ViewBigImageActivity 里面好像有内存泄漏

### ISSUE THREAD

**Issue by MichaelXcy** [youlookwhat/CloudReader#77]
@youlookwhat 大神你好，首先感谢你的开源项目，给予了我很大的帮助。正在学习安卓，以前都是用eclipse开发，现在从as入手，像学习下MVP以及MVVM模式的开发。

编译了这个项目的最新代码跑起来，内容是没问题的，真棒。
但是好像Leaks 这个模块里面会提示有内存泄漏，主要是ViewBigImageActivity 里面泄漏。这个问题有时间的话麻烦帮忙查一下是什么原因？多谢。

**Comment by youlookwhat** [comment]
@MichaelXcy 能不能提供Leaks的相关截图信息
