### ISSUE TITLE
编译不通过。

### ISSUE THREAD

**Issue by qflbai** [youlookwhat/CloudReader#78]
我下载完成后，无法编译成功。

**Comment by youlookwhat** [comment]
提供下错误截图，因为我这边是好的

**Comment by youlookwhat** [comment]
@qflbai 将签名部分的代码注释掉

**Comment by qflbai** [comment]
![qq 20180717092729](https://user-images.githubusercontent.com/23705172/42791560-ce703290-89a3-11e8-87ff-5f7458877d43.png)
签名文件我之前注释过，注释玩之后，就是这样的，我尝试过解决，但没成功。

**Comment by qflbai** [comment]
![qq 20180717093325](https://user-images.githubusercontent.com/23705172/42791736-b2c4c0b4-89a4-11e8-8d04-507038fc5642.png)
现在解决了，我替换了这两处  google()与jcenter()的位置，就编译成功了，麻烦楼主了。

**Comment by youlookwhat** [comment]
那就好。你是不是没有翻墙导致编译不过？

**Comment by qflbai** [comment]
不是，可能是android studio3.1.3这个最新版本导致的。

**Comment by youlookwhat** [comment]
没问题就好。
```java
buildscript {
    repositories {
        jcenter()
        google()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.1.3'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}
```
我这边更新为3.1.3了，没有发现什么问题。
