### ISSUE TITLE
banner库版本修改 导致的编译失败 

### ISSUE THREAD

**Issue by QianChaoGit** [youlookwhat/CloudReader#79]
如果依赖此版本库compile 'com.youth.banner:banner:1.4.1' 编译会不通过 报错 程序包databinding不存在，其他版本的banner库可以正常编译 因为我接手的项目中使用com.youth.banner也遇到了此类问题（ banner库只要改成非1.4.1版本的 就会编译不通过，报错 程序包databinding不存在，1.4.1版本能正常编译）
下面是cloudReader的报错日志
[error.txt](https://github.com/youlookwhat/CloudReader/files/2208036/error.txt)

**Comment by QianChaoGit** [comment]
![Uploading (O(`$$~4M14($71~RT~BPSJ.png…]()

**Comment by youlookwhat** [comment]
我用的 implementation 'com.youth.banner:banner:1.4.10' ，没有发现什么问题啊

**Comment by QianChaoGit** [comment]
没问题了 databinding定位不到错误 自己找到了
