### ISSUE TITLE
每日推荐，福利，干活定制，大安卓，下拉的时候会有一个红色的波纹是怎么实现的？

### ISSUE THREAD

**Issue by MariShunxiang** [youlookwhat/CloudReader#8]
每日推荐，福利，干活定制，大安卓，下拉的时候会有一个红色的波纹是怎么实现的？

**Comment by youlookwhat** [comment]
@MariShunxiang 父布局使用fragment或scrollview下拉会有阴影效果。颜色是你配置的主题上指定的颜色。

**Comment by MariShunxiang** [comment]
你的意思是这几个Fragment的容器的使用了FrameLayout布局是吗？

**Comment by youlookwhat** [comment]
是这个意思。父布局使用FrameLayout，不好意思，刚写错了。

**Comment by MariShunxiang** [comment]
没明白。。。

**Comment by youlookwhat** [comment]
那个波纹用RecyclerView就自己有了，在你需要产生波纹的布局外套一层FrameLayout或ScrollView也会有这样的效果。。

**Comment by MariShunxiang** [comment]
哦哦，多谢！

**Comment by youlookwhat** [comment]
好的
