### ISSUE TITLE
错误: 非法的表达式开始

### ISSUE THREAD

**Issue by yanxiaonuo** [youlookwhat/CloudReader#81]
![default](https://user-images.githubusercontent.com/33899039/42986550-8cd7c17c-8c28-11e8-9ea7-30510ce357e2.PNG)

**Comment by yanxiaonuo** [comment]
![default](https://user-images.githubusercontent.com/33899039/42986586-a8065b34-8c28-11e8-93b7-acbdfb426bc1.PNG)

**Comment by yanxiaonuo** [comment]
请问下这个怎么处理？

**Comment by youlookwhat** [comment]
下载最新的就好了
public static final String VERSION_NAME = "1.9.6";
