### ISSUE TITLE
编译遇到问题

### ISSUE THREAD

**Issue by fudiandong** [youlookwhat/CloudReader#82]
Could not get unknown property 'pStoreFile' for SigningConfig_Decorated

貌似是
// 注释下面代码(签名配置)
    signingConfigs {
        if (propertyHaveSigningConfigs) {
            debug {
                storeFile file(pStoreFile)
                storePassword pStorePassword
                keyAlias pKeyAlias
                keyPassword pKeyPassword
            }

            release {
                storeFile file(pStoreFile)
                storePassword pStorePassword
                keyAlias pKeyAlias
                keyPassword pKeyPassword
            }
        }
    }  
没找到 file，大神帮指点下

**Comment by youlookwhat** [comment]
注释掉签名代码部分
