### ISSUE TITLE
连接失败

### ISSUE THREAD

**Issue by SeaMyC** [youlookwhat/CloudReader#84]
Could not download ddmlib.jar (com.android.tools.ddms:ddmlib:26.1.2)

**Comment by SeaMyC** [comment]
//换个阿里云的代理就行了 
repositories {
        maven { url 'http://maven.aliyun.com/nexus/content/groups/public/' }
    }

**Comment by youlookwhat** [comment]
此应用里没有引用这个jar吧，解决了就好
