### ISSUE TITLE
福利模块的图片加载 用的什么框架？

### ISSUE THREAD

**Issue by gmloveyy** [youlookwhat/CloudReader#85]
我也在用福利接口  我的fragment里布局用grideview    自定义了adapter用Picasso加载图片     但是不知道为什么界面什么都看不到运行也不报错   想请教下你的福利这个接口是如何实现的   用的布局 图片加载框架等

**Comment by youlookwhat** [comment]
用的是RecyclerView的网格布局配合Glide加载的
