### ISSUE TITLE
采用2.2.2版本studio编译没通过

### ISSUE THREAD

**Issue by chinesebobo** [youlookwhat/CloudReader#86]
因为studio 版本为2.2.2 所以将 gradle改写为classpath 'com.android.tools.build:gradle:2.2.2' ,而且把项目中implementation改为compile,但是还是无法编译过去
![default](https://user-images.githubusercontent.com/20639304/47554821-d33c2700-d93c-11e8-91c4-17a856d61f9c.png)  
![default](https://user-images.githubusercontent.com/20639304/47554842-e51dca00-d93c-11e8-8b14-a2cd8d238b43.png)

**Comment by youlookwhat** [comment]
建议升级到 3.0以上
