### ISSUE TITLE
新增导航数据的列表滑动错位

### ISSUE THREAD

**Issue by WengHaobin** [youlookwhat/CloudReader#87]
右侧列表滑到底部的时候，左侧列表滑动到右侧可见的第一个item对应的位置，也就是说右侧到底了，左侧还没到底。
![image](https://user-images.githubusercontent.com/16800049/47778398-c56a1580-dd31-11e8-8e9a-3406aab66df8.png)

**Comment by youlookwhat** [comment]
嗯，是的 ，因为左边定位 取的是右边页面的第一条是哪一类，而右边滑到底后由于最后一类不够内容不够，所以左边没有定位到最后一条的条目那里。可能有点怪，但这个逻辑是正常的，感谢使用~

**Comment by youlookwhat** [comment]
但是你滑到最顶端或最尾端也是有问题的。它的item无法定位到中间。

**Comment by WengHaobin** [comment]
![haha](https://user-images.githubusercontent.com/16800049/48458338-d9694900-e800-11e8-9dc5-f0da3f96b609.gif)
这是我的实现效果

**Comment by WengHaobin** [comment]
这是我的实现效果 
![haha](https://user-images.githubusercontent.com/16800049/48458569-e5093f80-e801-11e8-894b-89f6b74884af.gif)

**Comment by WengHaobin** [comment]
![haha](https://user-images.githubusercontent.com/16800049/48462816-c3658380-e814-11e8-9483-f63393f4a1e7.gif)
实现方式如图

**Comment by WengHaobin** [comment]
![haha](https://user-images.githubusercontent.com/16800049/48463672-d594f100-e817-11e8-8de8-7b1f246830d4.gif)
实现效果如图

**Comment by youlookwhat** [comment]
实现的很好啊，可以的。想把这个页面结构给改一下，这个界面看起来太沉重了

**Comment by youlookwhat** [comment]
里面的结构改了大部分，新的页面出来了，这个就关闭了，有什么问题再提吧
