### ISSUE TITLE
 电影OneFragment跳转<->回退异常

### ISSUE THREAD

**Issue by Cazaea** [youlookwhat/CloudReader#89]
在外层ViewPager包含的三个Fragment中，OneFragment所引用的OneAdapter第43行，不能排除快速双击造成的异常，请您查看修复一下。

我在应用时，擅自修改成了：

` 
     // 不能排除快速双击困扰
    // binding.setCallback(subjectsBean -> OneMovieDetailActivity.start(activity, positionData, binding.ivOnePhoto));

                binding.llOneItem.setOnClickListener(new PerfectClickListener() {
                        @Override
                        protected void onNoDoubleClick(View v) {
                            OneMovieDetailActivity.start(activity, positionData, binding.ivOnePhoto);
                        }
                });

`

或者是否要修改一下OneItemCallback

**Comment by youlookwhat** [comment]
嗯，这是一个问题，后期会修改👌

**Comment by Cazaea** [comment]
OK

**Comment by youlookwhat** [comment]
已完善，d6d81fffdb2f3731107ee41f7e51c6414c312ea4
