### ISSUE TITLE
API数据问题

### ISSUE THREAD

**Issue by 1040087877** [youlookwhat/CloudReader#9]
- 每日推荐新闻的API   每日数据： http://gank.io/api/day/年/月/日
有时候API访问会出现连续两天没有数据 比如
http://gank.io/api/day/2017/1/18 今天的 没有数据
http://gank.io/api/day/2017/1/17 昨天的 没有数据
http://gank.io/api/day/2017/1/16 前天的 有数据
- 会导致App 有时候不能正常获取数据

- 建议弄个逐渐递减的方法，如果找不到数据就一直往前递减，可以保证正常出现数据

**Comment by youlookwhat** [comment]
之前也有想过，欧克  这就可以加上

**Comment by youlookwhat** [comment]
@1040087877 实现了但感觉不太好，假如过年上十天都没有数据，那么我要请求上十次了

**Comment by 1040087877** [comment]
好的 没关系 我刚才 自己也实现出来了

**Comment by youlookwhat** [comment]
你用的windows吗，是不是昨天的包，能不能下载昨天的包试一下，看有没有出什么问题。databinding那块好像又有点毛病..

**Comment by 1040087877** [comment]
好的  是windows 我等会更新一下，看能不能正常运行

**Comment by 1040087877** [comment]
不知道为什么 在genymotion 模拟器里 进入网页播放html5视频 只有声音 但是画面黑屏，但是在真机上正常显示

**Comment by 1040087877** [comment]
@youlookwhat   没问题，更新后 可以正常运行

**Comment by youlookwhat** [comment]
@1040087877 我刚在genymotion 模拟器里试了，发现视频是可以看到画面的，是不是个别视频的原因。因为有人反映下载后databinding报错，我担心是哪里又改错了，没事就放心了，谢谢了哈

**Comment by 1040087877** [comment]
(＾－＾)V 确实是我的模拟器问题，我用自带浏览器也不行，辛苦了哈

**Comment by youlookwhat** [comment]
恩恩  你也辛苦了😄
