### ISSUE TITLE
是否考虑采用RxJava2.x封装http?

### ISSUE THREAD

**Issue by Cazaea** [youlookwhat/CloudReader#91]

**Comment by youlookwhat** [comment]
现在不是的吗？

**Comment by Cazaea** [comment]
现在的不是基于1.3.0rx包的链式调用？
`// 用于链式调用
    api 'io.reactivex:rxandroid:1.2.1'
    // api 'io.reactivex:rxandroid:2.1.0'
    // 使用adapter-rxjava 将 compile 替换为 implementation 会报错
    // 因为implementation只能用在本项目中，主app项目不能引用 https://www.jianshu.com/p/f34c179bc9d0
    api 'com.squareup.retrofit2:adapter-rxjava:2.4.0'
    // api 'com.squareup.retrofit2:adapter-rxjava2:2.4.0'`
可能是，我还没有看懂...

**Comment by youlookwhat** [comment]
那就是1.0+了的，之前写的，没出问题就一直没有换，后期考虑换吧

**Comment by Cazaea** [comment]
咨询您个问题：我参考您的框架，进行项目搭建，您的项目并没有出现全屏页面跳转非全屏页面的布局抖动问题，我的几乎跟您的一样，为什么会出这种问题呢？您在平常工作撸代码的时候遇到这个问题了吗？具体是哪些情况导致的呢？

**Comment by youlookwhat** [comment]
能说的具体点吗，或者是提供视频演示，我理解的可能是切到下一页面的卡顿问题，是通过延迟加载避免的。

**Comment by Cazaea** [comment]
就是从全屏页面点击一个按钮，跳转到一个非全屏的页面（这个页面有StatusBar+TitleBar），非全屏页面从下往上弹出（此时似乎没有了StatusBar的高度），在动画走完时，这个非全屏页面突然向下抽动一下，在最上边强行重新加了StatusBar，如果没说清楚，我明天做一个GIf图给你

**Comment by youlookwhat** [comment]
是不是 StatusBar 设置有问题，在页面B初始化的时候就设置，这样打开B就有StatusBar，而不会显示后向下移动。或者换一种 设置 StatusBar 的方式

**Comment by Cazaea** [comment]
好的，谢谢您了，我按照您的思路先整理一下

**Comment by youlookwhat** [comment]
fix https://github.com/youlookwhat/CloudReader/issues/99 已经升级到RxJava 2.x

**Comment by youlookwhat** [comment]
@Cazaea 具体代码 具体代码 9c30ac90821b2d3080d8f0877135ca32b8d36537
