### ISSUE TITLE
构建失败

### ISSUE THREAD

**Issue by hellohanyu** [youlookwhat/CloudReader#92]
Could not resolve all dependencies for configuration ':app:debugRuntimeClasspath'.
Could not determine artifacts for com.tencent.bugly:crashreport:2.6.6.1
Could not get resource 'https://jcenter.bintray.com/com/tencent/bugly/crashreport/2.6.6.1/crashreport-2.6.6.1.aar'.
Could not HEAD 'https://jcenter.bintray.com/com/tencent/bugly/crashreport/2.6.6.1/crashreport-2.6.6.1.aar'.
Connect to d29vzk4ow07wi7.cloudfront.net:443 [d29vzk4ow07wi7.cloudfront.net/52.85.83.4, d29vzk4ow07wi7.cloudfront.net/52.85.83.8, d29vzk4ow07wi7.cloudfront.net/52.85.83.17, d29vzk4ow07wi7.cloudfront.net/52.85.83.233] failed: Read timed out
Read timed out

**Comment by youlookwhat** [comment]
将bugly引入和Application里的初始化代码注释一下试试

**Comment by hellohanyu** [comment]
> 
> 
> 将bugly引入和Application里的初始化代码注释一下试试

打开科学上网后已解决
