### ISSUE TITLE
上拉加载 mPage控制有问题

### ISSUE THREAD

**Issue by LeoGallary** [youlookwhat/CloudReader#93]
上拉加载的mPage在网络出错是需要 mPage--，不考虑缓存的情况下，可能出现错乱

**Comment by youlookwhat** [comment]
不明白具体什么意思，能说明具体的页面，操作情况吗？

**Comment by LeoGallary** [comment]
首次进入页面，请求第一页数据成功。下拉加载请求第二页失败，这个时候再下拉加载一次，请求第三页了，跳过了第二页。

**Comment by LeoGallary** [comment]
我只看了BannerFragement的recycleview

**Comment by youlookwhat** [comment]
好的，已经发现了，正在改~

**Comment by youlookwhat** [comment]
@LeoGallary 已解决，更新版本就好了
