### ISSUE TITLE
有考虑转移到AndroidX吗？

### ISSUE THREAD

**Issue by sweetwong** [youlookwhat/CloudReader#98]
我看了谷歌一些开源项目，已经转移到AndroidX了
谷歌也说后面只更新AndroidX，不更换新Support系列了
以及Material Design和Material Theming也是基于AndroidX的
以及基于AndroidX可以对单独对Fragment进行测试

**Comment by youlookwhat** [comment]
可以考虑，后期会着手做这个

**Comment by lydlovezjr** [comment]
强烈要求适配Android X

**Comment by youlookwhat** [comment]
正在着手

**Comment by youlookwhat** [comment]
@sweetwong @lydlovezjr 已升级到AndroidX，可拉最新的代码查看啦 https://github.com/youlookwhat/CloudReader/commit/8176c3399c7bd6246bc721bf5097d07bfa6c36b7

**Comment by lydlovezjr** [comment]
大佬,牛逼
