### ISSUE TITLE
您好，请问什么时候能升级到RxJava2.x呢？

### ISSUE THREAD

**Issue by wotoutengleha** [youlookwhat/CloudReader#99]

**Comment by youlookwhat** [comment]
马上升级 一直想着手了

**Comment by youlookwhat** [comment]
具体代码 9c30ac90821b2d3080d8f0877135ca32b8d36537

**Comment by wotoutengleha** [comment]
非常感谢  ，我获取了最新代码  viewModel 和model中的网络请求代码基本大面积都是黄色警告，我的编辑器是3.2.1  the result of subscribe is not used 出现这个警告，看着很不舒服，请问是什么原因呢

**Comment by youlookwhat** [comment]
能给个截图吗  我这边还没看到  没有使用subscribe 应该没有影响

**Comment by wotoutengleha** [comment]
<img width="1111" alt="wx20190225-150347 2x" src="https://user-images.githubusercontent.com/15045363/53319849-baee1000-390e-11e9-9f32-269bdae66628.png">
![1551078267461](https://user-images.githubusercontent.com/15045363/53319852-bde90080-390e-11e9-8381-f028a3c490cb.jpg)
就是这种的 ViewModel中基本都有

**Comment by youlookwhat** [comment]
你看一下这个类有没有类似的提示：ArticleListViewModel.java

**Comment by wotoutengleha** [comment]
<img width="1381" alt="111" src="https://user-images.githubusercontent.com/15045363/53320077-73b44f00-390f-11e9-9938-d1f6c6e8962a.png">

**Comment by wotoutengleha** [comment]
这个类也有的

**Comment by youlookwhat** [comment]
刚升级了Android Studio，是没有处理返回值 Disposable subscribe 。添加个忽略就好，可以不用处理的。

**Comment by youlookwhat** [comment]
先关闭了，有什么问题再开个吧
